source "https://rubygems.org"

gem "nanoc", "~> 3.8.0"
gem "mime-types"
gem "builder"
gem "adsf"
gem "compass"
gem "compass-blueprint"
gem "foreman"
gem "slim"
gem "maruku"
gem "nokogiri"
gem "pygments.rb"
gem "rake"
gem "colored"
gem "deadweight"
